### Test Loop webhook – basic subscription
POST http://localhost:2222/api/v1/webhooks/loop
Content-Type: application/json

{
  "event": "subscription.updated",
  "data": {
    "id": 11099371,
    "status": "ACTIVE"
  }
}

### Test Loop webhook – basic customer
POST http://localhost:2222/api/v1/webhooks/loop
Content-Type: application/json

{
  "event": "customer.updated",
  "data": {
    "id": 7685144412482
  }
}
