### Get all Segments
GET {{URL}}getallwheelsegments

###
PUT http://localhost:2222/api/v1/1/wheelsegment
Content-Type: application/json

{
  "wheelId": 1,
  "position": 1,
  "type": "PRIZE",
  "title": "test",
  "imageUrl": "wegrdzgnd",
  "prizeName": "PRIZE",
  "discountCode": "test",
  "productSku": "test",
  "active": false
}

### Check eligibility (email)
POST http://localhost:2222/api/v1/customer/check-eligibility
Content-Type: application/json

{
  "emailOrPhone": "email@emaitest.httpl.dk"
}



### Check eligibility (phone)
POST http://localhost:2222/api/v1/customer/check-eligibility
Content-Type: application/json

{
  "emailOrPhone": "12211221"
}
